/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.api;

import com.cobo.waas2.ApiClient;
import com.cobo.waas2.ApiException;
import com.cobo.waas2.Configuration;
import com.cobo.waas2.model.CreateSweepToAddress;
import com.cobo.waas2.model.ErrorResponse;
import com.cobo.waas2.model.ListWalletSweepToAddresses200Response;
import com.cobo.waas2.model.SweepToAddress;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AutoSweepApi
 */
@Disabled
public class AutoSweepApiTest {
    ApiClient defaultClient = Configuration.getDefaultApiClient();
    // set custom base url
    {
        defaultClient.setBasePath("https://api.sandbox.cobo.com/v2");
        defaultClient.setPrivKey("<YOUR_API_PRIVATE_KEY_IN_HEX>");
    }
    private final AutoSweepApi api = new AutoSweepApi();

    /**
     * create wallet sweep to addresses
     *
     * This operation create a new sweep to address for the wallet. The old sweep to address will become invalid. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createWalletSweepToAddressesTest() throws ApiException {
        CreateSweepToAddress createSweepToAddress = null;
        SweepToAddress response = api.createWalletSweepToAddresses(createSweepToAddress);
        // TODO: test validations
    }

    /**
     * List wallet sweep to addresses
     *
     * This operation retrieves a list of sweep to addresses within your wallet. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listWalletSweepToAddressesTest() throws ApiException {
        UUID walletId = null;
        ListWalletSweepToAddresses200Response response = api.listWalletSweepToAddresses(walletId);
        // TODO: test validations
    }

}
