/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.api;

import com.cobo.waas2.ApiClient;
import com.cobo.waas2.ApiException;
import com.cobo.waas2.Configuration;
import com.cobo.waas2.model.ErrorResponse;
import com.cobo.waas2.model.SetSupportTokenParams;
import com.cobo.waas2.model.SetSupportTokenResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InternalTokensApi
 */
@Disabled
public class InternalTokensApiTest {
    ApiClient defaultClient = Configuration.getDefaultApiClient();
    // set custom base url
    {
        defaultClient.setBasePath("https://api.sandbox.cobo.com/v2");
        defaultClient.setPrivKey("<YOUR_API_PRIVATE_KEY_IN_HEX>");
    }
    private final InternalTokensApi api = new InternalTokensApi();

    /**
     * Set support token
     *
     * This operation sets a supported token for specified payment organizations. You need to specify the token ID, organization IDs, and wallet type. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void setSupportTokenTest() throws ApiException {
        SetSupportTokenParams setSupportTokenParams = null;
        SetSupportTokenResponse response = api.setSupportToken(setSupportTokenParams);
        // TODO: test validations
    }

}
