/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.api;

import com.cobo.waas2.ApiClient;
import com.cobo.waas2.ApiException;
import com.cobo.waas2.Configuration;
import com.cobo.waas2.model.ErrorResponse;
import com.cobo.waas2.model.GetReconciliationLedger200Response;
import com.cobo.waas2.model.ListReconciliationStatements200Response;
import java.time.LocalDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ReconciliationApi
 */
@Disabled
public class ReconciliationApiTest {
    ApiClient defaultClient = Configuration.getDefaultApiClient();
    // set custom base url
    {
        defaultClient.setBasePath("https://api.sandbox.cobo.com/v2");
        defaultClient.setPrivKey("<YOUR_API_PRIVATE_KEY_IN_HEX>");
    }
    private final ReconciliationApi api = new ReconciliationApi();

    /**
     * Get reconciliation ledger
     *
     * This operation retrieves the post-transaction balance (running balance) for the specified transactions, used for stablecoin deposit and withdrawal reconciliation.  You need to provide the transaction IDs in &#x60;transaction_ids&#x60;. Each returned entry includes the signed amount and the resulting balance of the address after the transaction, expressed in the token&#39;s main unit.  &lt;Note&gt;This operation is available to selected customers only. To request access, please contact Cobo.&lt;/Note&gt;  &lt;Note&gt;This operation is applicable to MPC Wallets and Custodial Web3 Wallets only, and covers stablecoins only. To ensure accurate reconciliation results, do not use the contract call and message signing features. Currently, only stablecoins on the Ethereum and TRON chains are supported.&lt;/Note&gt; 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getReconciliationLedgerTest() throws ApiException {
        String transactionIds = null;
        GetReconciliationLedger200Response response = api.getReconciliationLedger(transactionIds);
        // TODO: test validations
    }

    /**
     * List reconciliation daily statements
     *
     * This operation retrieves daily reconciliation statements within a date range. Each statement contains the opening balance, total deposits, total withdrawals, and closing balance for a business date, wallet, and token.  You need to specify the date range with &#x60;start_date&#x60; and &#x60;end_date&#x60;. You can filter the results by wallets and tokens, and paginate the query results. All amounts are expressed in the token&#39;s main unit.  &lt;Note&gt;This operation is available to selected customers only. To request access, please contact Cobo.&lt;/Note&gt;  &lt;Note&gt;This operation is applicable to MPC Wallets and Custodial Web3 Wallets only, and covers stablecoins only. To ensure accurate reconciliation results, do not use the contract call and message signing features. Currently, only stablecoins on the Ethereum and TRON chains are supported.&lt;/Note&gt; 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listReconciliationStatementsTest() throws ApiException {
        LocalDate startDate = null;
        LocalDate endDate = null;
        String walletIds = null;
        String tokenIds = null;
        Integer limit = null;
        String before = null;
        String after = null;
        ListReconciliationStatements200Response response = api.listReconciliationStatements(startDate, endDate, walletIds, tokenIds, limit, before, after);
        // TODO: test validations
    }

}
