/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * RBF type. - &#x60;Drop&#x60;: Drop the payout. - &#x60;SpeedUp&#x60;: Speed up the payout. 
 */
@JsonAdapter(BatchPayoutRbfType.Adapter.class)
public enum BatchPayoutRbfType {
  UNKNOWN(null),
  
  DROP("Drop"),
  
  SPEEDUP("SpeedUp");

  private String value;

  BatchPayoutRbfType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static BatchPayoutRbfType fromValue(String value) {
    for (BatchPayoutRbfType b : BatchPayoutRbfType.values()) {
      if (b == UNKNOWN) continue;
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN;
    // throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<BatchPayoutRbfType> {
    @Override
    public void write(final JsonWriter jsonWriter, final BatchPayoutRbfType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public BatchPayoutRbfType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return BatchPayoutRbfType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    BatchPayoutRbfType.fromValue(value);
  }
}

