/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The source of the destination: - &#x60;Client&#x60;: The destination was created by the client. - &#x60;System&#x60;: The destination was created by the system. 
 */
@JsonAdapter(DestinationSource.Adapter.class)
public enum DestinationSource {
  UNKNOWN(null),
  
  CLIENT("Client"),
  
  SYSTEM("System");

  private String value;

  DestinationSource(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static DestinationSource fromValue(String value) {
    for (DestinationSource b : DestinationSource.values()) {
      if (b == UNKNOWN) continue;
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN;
    // throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<DestinationSource> {
    @Override
    public void write(final JsonWriter jsonWriter, final DestinationSource enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public DestinationSource read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return DestinationSource.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    DestinationSource.fromValue(value);
  }
}

