/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The transaction fee level. Specify this property if you want Cobo to calculate the transaction fee for you based on the selected level, instead of providing the fee-related properties yourself. Possible values are: - &#x60;Slow&#x60;: A lower transaction fee, which may lead to a longer confirmation time. - &#x60;Recommended&#x60;: The recommended transaction fee, which balances the fee cost and the confirmation time. - &#x60;Fast&#x60;: A higher transaction fee for a shorter confirmation time.  You can call [Estimate transaction fee](https://www.cobo.com/developers/v2/api-references/transactions/estimate-transaction-fee) to view the estimated transaction fee of each fee level.  &lt;Note&gt;You cannot specify both &#x60;fee_level&#x60; and &#x60;fee&#x60; in the same request. If you specify both, the request fails.&lt;/Note&gt;  &lt;Note&gt;This property does not take effect in the following cases, and the transaction fee is determined by Cobo: - The transaction uses the fixed fee model. For more information about the fee models, refer to [Fee models](https://www.cobo.com/developers/v2/guides/transactions/estimate-fees#fee-models). - The transaction is initiated from Custodial Wallets (Asset Wallets) or Exchange Wallets. &lt;/Note&gt; 
 */
@JsonAdapter(FeeLevel.Adapter.class)
public enum FeeLevel {
  UNKNOWN(null),
  
  SLOW("Slow"),
  
  RECOMMENDED("Recommended"),
  
  FAST("Fast");

  private String value;

  FeeLevel(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static FeeLevel fromValue(String value) {
    for (FeeLevel b : FeeLevel.values()) {
      if (b == UNKNOWN) continue;
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN;
    // throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<FeeLevel> {
    @Override
    public void write(final JsonWriter jsonWriter, final FeeLevel enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public FeeLevel read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return FeeLevel.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    FeeLevel.fromValue(value);
  }
}

