/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.cobo.waas2.JSON;

/**
 * FeeStationDetailGasFuelStrategiesInner
 */
@javax.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen", 
    comments = "Generator version: 7.6.0"
)
public class FeeStationDetailGasFuelStrategiesInner {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_CHAIN_IDENTIFY = "chain_identify";
  @SerializedName(SERIALIZED_NAME_CHAIN_IDENTIFY)
  private String chainIdentify;

  public static final String SERIALIZED_NAME_FEE_STATION_ID = "fee_station_id";
  @SerializedName(SERIALIZED_NAME_FEE_STATION_ID)
  private String feeStationId;

  /**
   * - -1: Unknown - 0: 不使用加油功能 - 1: 被动使用gas station功能：当地址余额不足时，gas station地址将交易支付手续费 - 2: 所有交易的手续费由gas station地址支付 - 3: 加油交易，使用 portal 侧的配置 
   */
  @JsonAdapter(FuelTypeEnum.Adapter.class)
  public enum FuelTypeEnum {
    NUMBER_MINUS_1(-1),
    
    NUMBER_0(0),
    
    NUMBER_1(1),
    
    NUMBER_2(2),
    
    NUMBER_3(3);

    private Integer value;

    FuelTypeEnum(Integer value) {
      this.value = value;
    }

    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static FuelTypeEnum fromValue(Integer value) {
      for (FuelTypeEnum b : FuelTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<FuelTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FuelTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public FuelTypeEnum read(final JsonReader jsonReader) throws IOException {
        Integer value =  jsonReader.nextInt();
        return FuelTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      Integer value = jsonElement.getAsInt();
      FuelTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_FUEL_TYPE = "fuel_type";
  @SerializedName(SERIALIZED_NAME_FUEL_TYPE)
  private FuelTypeEnum fuelType;

  public static final String SERIALIZED_NAME_PRIORITY = "priority";
  @SerializedName(SERIALIZED_NAME_PRIORITY)
  private Integer priority;

  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    NUMBER_0(0),
    
    NUMBER_1(1),
    
    NUMBER_2(2),
    
    NUMBER_3(3);

    private Integer value;

    StatusEnum(Integer value) {
      this.value = value;
    }

    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(Integer value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        Integer value =  jsonReader.nextInt();
        return StatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      Integer value = jsonElement.getAsInt();
      StatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private StatusEnum status;

  public static final String SERIALIZED_NAME_CREATED_TIME = "created_time";
  @SerializedName(SERIALIZED_NAME_CREATED_TIME)
  private Integer createdTime;

  public static final String SERIALIZED_NAME_UPDATED_TIME = "updated_time";
  @SerializedName(SERIALIZED_NAME_UPDATED_TIME)
  private Integer updatedTime;

  public FeeStationDetailGasFuelStrategiesInner() {
  }

  public FeeStationDetailGasFuelStrategiesInner id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  public FeeStationDetailGasFuelStrategiesInner chainIdentify(String chainIdentify) {
    this.chainIdentify = chainIdentify;
    return this;
  }

   /**
   * Get chainIdentify
   * @return chainIdentify
  **/
  @javax.annotation.Nullable
  public String getChainIdentify() {
    return chainIdentify;
  }

  public void setChainIdentify(String chainIdentify) {
    this.chainIdentify = chainIdentify;
  }


  public FeeStationDetailGasFuelStrategiesInner feeStationId(String feeStationId) {
    this.feeStationId = feeStationId;
    return this;
  }

   /**
   * Get feeStationId
   * @return feeStationId
  **/
  @javax.annotation.Nullable
  public String getFeeStationId() {
    return feeStationId;
  }

  public void setFeeStationId(String feeStationId) {
    this.feeStationId = feeStationId;
  }


  public FeeStationDetailGasFuelStrategiesInner fuelType(FuelTypeEnum fuelType) {
    this.fuelType = fuelType;
    return this;
  }

   /**
   * - -1: Unknown - 0: 不使用加油功能 - 1: 被动使用gas station功能：当地址余额不足时，gas station地址将交易支付手续费 - 2: 所有交易的手续费由gas station地址支付 - 3: 加油交易，使用 portal 侧的配置 
   * @return fuelType
  **/
  @javax.annotation.Nullable
  public FuelTypeEnum getFuelType() {
    return fuelType;
  }

  public void setFuelType(FuelTypeEnum fuelType) {
    this.fuelType = fuelType;
  }


  public FeeStationDetailGasFuelStrategiesInner priority(Integer priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * @return priority
  **/
  @javax.annotation.Nullable
  public Integer getPriority() {
    return priority;
  }

  public void setPriority(Integer priority) {
    this.priority = priority;
  }


  public FeeStationDetailGasFuelStrategiesInner status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  public FeeStationDetailGasFuelStrategiesInner createdTime(Integer createdTime) {
    this.createdTime = createdTime;
    return this;
  }

   /**
   * Get createdTime
   * @return createdTime
  **/
  @javax.annotation.Nullable
  public Integer getCreatedTime() {
    return createdTime;
  }

  public void setCreatedTime(Integer createdTime) {
    this.createdTime = createdTime;
  }


  public FeeStationDetailGasFuelStrategiesInner updatedTime(Integer updatedTime) {
    this.updatedTime = updatedTime;
    return this;
  }

   /**
   * Get updatedTime
   * @return updatedTime
  **/
  @javax.annotation.Nullable
  public Integer getUpdatedTime() {
    return updatedTime;
  }

  public void setUpdatedTime(Integer updatedTime) {
    this.updatedTime = updatedTime;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the FeeStationDetailGasFuelStrategiesInner instance itself
   */
  public FeeStationDetailGasFuelStrategiesInner putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeeStationDetailGasFuelStrategiesInner feeStationDetailGasFuelStrategiesInner = (FeeStationDetailGasFuelStrategiesInner) o;
    return Objects.equals(this.id, feeStationDetailGasFuelStrategiesInner.id) &&
        Objects.equals(this.chainIdentify, feeStationDetailGasFuelStrategiesInner.chainIdentify) &&
        Objects.equals(this.feeStationId, feeStationDetailGasFuelStrategiesInner.feeStationId) &&
        Objects.equals(this.fuelType, feeStationDetailGasFuelStrategiesInner.fuelType) &&
        Objects.equals(this.priority, feeStationDetailGasFuelStrategiesInner.priority) &&
        Objects.equals(this.status, feeStationDetailGasFuelStrategiesInner.status) &&
        Objects.equals(this.createdTime, feeStationDetailGasFuelStrategiesInner.createdTime) &&
        Objects.equals(this.updatedTime, feeStationDetailGasFuelStrategiesInner.updatedTime)&&
        Objects.equals(this.additionalProperties, feeStationDetailGasFuelStrategiesInner.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, chainIdentify, feeStationId, fuelType, priority, status, createdTime, updatedTime, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeeStationDetailGasFuelStrategiesInner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    chainIdentify: ").append(toIndentedString(chainIdentify)).append("\n");
    sb.append("    feeStationId: ").append(toIndentedString(feeStationId)).append("\n");
    sb.append("    fuelType: ").append(toIndentedString(fuelType)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    createdTime: ").append(toIndentedString(createdTime)).append("\n");
    sb.append("    updatedTime: ").append(toIndentedString(updatedTime)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("chain_identify");
    openapiFields.add("fee_station_id");
    openapiFields.add("fuel_type");
    openapiFields.add("priority");
    openapiFields.add("status");
    openapiFields.add("created_time");
    openapiFields.add("updated_time");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to FeeStationDetailGasFuelStrategiesInner
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!FeeStationDetailGasFuelStrategiesInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in FeeStationDetailGasFuelStrategiesInner is not found in the empty JSON string", FeeStationDetailGasFuelStrategiesInner.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("chain_identify") != null && !jsonObj.get("chain_identify").isJsonNull()) && !jsonObj.get("chain_identify").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `chain_identify` to be a primitive type in the JSON string but got `%s`", jsonObj.get("chain_identify").toString()));
      }
      if ((jsonObj.get("fee_station_id") != null && !jsonObj.get("fee_station_id").isJsonNull()) && !jsonObj.get("fee_station_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fee_station_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fee_station_id").toString()));
      }
      // validate the optional field `fuel_type`
      if (jsonObj.get("fuel_type") != null && !jsonObj.get("fuel_type").isJsonNull()) {
        FuelTypeEnum.validateJsonElement(jsonObj.get("fuel_type"));
      }
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        StatusEnum.validateJsonElement(jsonObj.get("status"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FeeStationDetailGasFuelStrategiesInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FeeStationDetailGasFuelStrategiesInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FeeStationDetailGasFuelStrategiesInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FeeStationDetailGasFuelStrategiesInner.class));

       return (TypeAdapter<T>) new TypeAdapter<FeeStationDetailGasFuelStrategiesInner>() {
           @Override
           public void write(JsonWriter out, FeeStationDetailGasFuelStrategiesInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() == null)
                   obj.addProperty(entry.getKey(), (String) null);
                 else if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public FeeStationDetailGasFuelStrategiesInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             FeeStationDetailGasFuelStrategiesInner instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of FeeStationDetailGasFuelStrategiesInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of FeeStationDetailGasFuelStrategiesInner
  * @throws IOException if the JSON string is invalid with respect to FeeStationDetailGasFuelStrategiesInner
  */
  public static FeeStationDetailGasFuelStrategiesInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FeeStationDetailGasFuelStrategiesInner.class);
  }

 /**
  * Convert an instance of FeeStationDetailGasFuelStrategiesInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

