/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The current status of the force sweep request: - &#x60;Pending&#x60;: The force sweep request has been created and is awaiting processing. - &#x60;Processing&#x60;: The force sweep request is currently being processed. - &#x60;Completed&#x60;: All requested force sweep have been completed. 
 */
@JsonAdapter(ForceSweepStatus.Adapter.class)
public enum ForceSweepStatus {
  UNKNOWN(null),
  
  PENDING("Pending"),
  
  PROCESSING("Processing"),
  
  COMPLETED("Completed");

  private String value;

  ForceSweepStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ForceSweepStatus fromValue(String value) {
    for (ForceSweepStatus b : ForceSweepStatus.values()) {
      if (b == UNKNOWN) continue;
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN;
    // throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ForceSweepStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final ForceSweepStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ForceSweepStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ForceSweepStatus.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    ForceSweepStatus.fromValue(value);
  }
}

