/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The transaction type. Possible values include:    - &#x60;Deposit&#x60;: A deposit transaction.   - &#x60;Withdrawal&#x60;: A withdrawal transaction. 
 */
@JsonAdapter(KytScreeningsTransactionType.Adapter.class)
public enum KytScreeningsTransactionType {
  UNKNOWN(null),
  
  DEPOSIT("Deposit"),
  
  WITHDRAWAL("Withdrawal");

  private String value;

  KytScreeningsTransactionType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static KytScreeningsTransactionType fromValue(String value) {
    for (KytScreeningsTransactionType b : KytScreeningsTransactionType.values()) {
      if (b == UNKNOWN) continue;
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN;
    // throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<KytScreeningsTransactionType> {
    @Override
    public void write(final JsonWriter jsonWriter, final KytScreeningsTransactionType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public KytScreeningsTransactionType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return KytScreeningsTransactionType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    KytScreeningsTransactionType.fromValue(value);
  }
}

