/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The merchant type. Possible values include: - &#x60;B2B&#x60;: Business-to-business merchant. - &#x60;B2C&#x60;: Business-to-consumer merchant. 
 */
@JsonAdapter(MerchantKycMerchantType.Adapter.class)
public enum MerchantKycMerchantType {
  UNKNOWN(null),
  
  B2B("B2B"),
  
  B2C("B2C");

  private String value;

  MerchantKycMerchantType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static MerchantKycMerchantType fromValue(String value) {
    for (MerchantKycMerchantType b : MerchantKycMerchantType.values()) {
      if (b == UNKNOWN) continue;
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN;
    // throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<MerchantKycMerchantType> {
    @Override
    public void write(final JsonWriter jsonWriter, final MerchantKycMerchantType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public MerchantKycMerchantType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return MerchantKycMerchantType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    MerchantKycMerchantType.fromValue(value);
  }
}

