/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The KYC submission status. Possible values include: - &#x60;PendingReview&#x60;: The KYC submission is pending review. - &#x60;Completed&#x60;: The KYC submission has been completed. - &#x60;Failed&#x60;: The KYC submission has failed. 
 */
@JsonAdapter(MerchantKycStatus.Adapter.class)
public enum MerchantKycStatus {
  UNKNOWN(null),
  
  PENDINGREVIEW("PendingReview"),
  
  COMPLETED("Completed"),
  
  FAILED("Failed");

  private String value;

  MerchantKycStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static MerchantKycStatus fromValue(String value) {
    for (MerchantKycStatus b : MerchantKycStatus.values()) {
      if (b == UNKNOWN) continue;
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN;
    // throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<MerchantKycStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final MerchantKycStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public MerchantKycStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return MerchantKycStatus.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    MerchantKycStatus.fromValue(value);
  }
}

