/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The business status of a pay-in transaction: - &#x60;Detected&#x60;: The incoming transaction has been detected but the funds are not yet available. - &#x60;PendingScreening&#x60;: The incoming transaction is awaiting a screening result. - &#x60;ActionRequired&#x60;: Action from the customer is required before processing can continue. - &#x60;Completed&#x60;: The funds are available for the corresponding Payments business object. - &#x60;Failed&#x60;: The incoming transaction cannot be credited. 
 */
@JsonAdapter(PaymentPayInStatus.Adapter.class)
public enum PaymentPayInStatus {
  UNKNOWN(null),
  
  DETECTED("Detected"),
  
  PENDINGSCREENING("PendingScreening"),
  
  ACTIONREQUIRED("ActionRequired"),
  
  COMPLETED("Completed"),
  
  FAILED("Failed");

  private String value;

  PaymentPayInStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PaymentPayInStatus fromValue(String value) {
    for (PaymentPayInStatus b : PaymentPayInStatus.values()) {
      if (b == UNKNOWN) continue;
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN;
    // throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<PaymentPayInStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final PaymentPayInStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PaymentPayInStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PaymentPayInStatus.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    PaymentPayInStatus.fromValue(value);
  }
}

