/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The screening service that reviews the incoming transaction
 */
@JsonAdapter(PaymentScreeningMode.Adapter.class)
public enum PaymentScreeningMode {
  UNKNOWN(null),
  
  COBOKYT("CoboKyt"),
  
  INTEGRATEDVENDOR("IntegratedVendor"),
  
  CUSTOMVENDOR("CustomVendor");

  private String value;

  PaymentScreeningMode(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PaymentScreeningMode fromValue(String value) {
    for (PaymentScreeningMode b : PaymentScreeningMode.values()) {
      if (b == UNKNOWN) continue;
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN;
    // throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<PaymentScreeningMode> {
    @Override
    public void write(final JsonWriter jsonWriter, final PaymentScreeningMode enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PaymentScreeningMode read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PaymentScreeningMode.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    PaymentScreeningMode.fromValue(value);
  }
}

