/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The status of the bank withdrawal: - &#x60;Pending&#x60;: The bank withdrawal has been created and is awaiting processing. - &#x60;Processing&#x60;: The bank withdrawal is being processed. - &#x60;Completed&#x60;: The bank withdrawal has been completed. - &#x60;Failed&#x60;: The bank withdrawal failed. 
 */
@JsonAdapter(PaymentBankWithdrawalStatus.Adapter.class)
public enum PaymentBankWithdrawalStatus {
  UNKNOWN(null),
  
  PENDING("Pending"),
  
  PROCESSING("Processing"),
  
  COMPLETED("Completed"),
  
  FAILED("Failed");

  private String value;

  PaymentBankWithdrawalStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PaymentBankWithdrawalStatus fromValue(String value) {
    for (PaymentBankWithdrawalStatus b : PaymentBankWithdrawalStatus.values()) {
      if (b == UNKNOWN) continue;
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN;
    // throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<PaymentBankWithdrawalStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final PaymentBankWithdrawalStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PaymentBankWithdrawalStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PaymentBankWithdrawalStatus.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    PaymentBankWithdrawalStatus.fromValue(value);
  }
}

