/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The reconciliation status of this daily statement row, captured **at the moment the day was closed**. Possible values include:   - &#x60;Confirmed&#x60;: All addresses of this wallet and token were reconciled against on-chain balances, so the figures in this row are trustworthy.   - &#x60;Halted&#x60;: At least one address failed the on-chain balance check, so reconciliation stopped there and the figures in this row may be incomplete or inaccurate.  Note this is a snapshot, not a live status: once a halted address is fixed, the row keeps reporting &#x60;Halted&#x60; until the day is reprocessed. 
 */
@JsonAdapter(ReconStatementStatus.Adapter.class)
public enum ReconStatementStatus {
  UNKNOWN(null),
  
  CONFIRMED("Confirmed"),
  
  HALTED("Halted");

  private String value;

  ReconStatementStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ReconStatementStatus fromValue(String value) {
    for (ReconStatementStatus b : ReconStatementStatus.values()) {
      if (b == UNKNOWN) continue;
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN;
    // throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ReconStatementStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final ReconStatementStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ReconStatementStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ReconStatementStatus.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    ReconStatementStatus.fromValue(value);
  }
}

