/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.cobo.waas2.model.ReconStatementStatus;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.cobo.waas2.JSON;

/**
 * The daily reconciliation statement for a wallet and token on a business date.
 */
@javax.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen", 
    comments = "Generator version: 7.6.0"
)
public class ReconDailyStatement {
  public static final String SERIALIZED_NAME_BIZ_DATE = "biz_date";
  @SerializedName(SERIALIZED_NAME_BIZ_DATE)
  private LocalDate bizDate;

  public static final String SERIALIZED_NAME_TOKEN_ID = "token_id";
  @SerializedName(SERIALIZED_NAME_TOKEN_ID)
  private String tokenId;

  public static final String SERIALIZED_NAME_CHAIN_ID = "chain_id";
  @SerializedName(SERIALIZED_NAME_CHAIN_ID)
  private String chainId;

  public static final String SERIALIZED_NAME_WALLET_ID = "wallet_id";
  @SerializedName(SERIALIZED_NAME_WALLET_ID)
  private UUID walletId;

  public static final String SERIALIZED_NAME_OPENING_BALANCE = "opening_balance";
  @SerializedName(SERIALIZED_NAME_OPENING_BALANCE)
  private String openingBalance;

  public static final String SERIALIZED_NAME_TOTAL_DEPOSIT = "total_deposit";
  @SerializedName(SERIALIZED_NAME_TOTAL_DEPOSIT)
  private String totalDeposit;

  public static final String SERIALIZED_NAME_DEPOSIT_COUNT = "deposit_count";
  @SerializedName(SERIALIZED_NAME_DEPOSIT_COUNT)
  private Integer depositCount;

  public static final String SERIALIZED_NAME_TOTAL_WITHDRAWAL = "total_withdrawal";
  @SerializedName(SERIALIZED_NAME_TOTAL_WITHDRAWAL)
  private String totalWithdrawal;

  public static final String SERIALIZED_NAME_WITHDRAWAL_COUNT = "withdrawal_count";
  @SerializedName(SERIALIZED_NAME_WITHDRAWAL_COUNT)
  private Integer withdrawalCount;

  public static final String SERIALIZED_NAME_CLOSING_BALANCE = "closing_balance";
  @SerializedName(SERIALIZED_NAME_CLOSING_BALANCE)
  private String closingBalance;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private ReconStatementStatus status;

  public ReconDailyStatement() {
  }

  public ReconDailyStatement bizDate(LocalDate bizDate) {
    this.bizDate = bizDate;
    return this;
  }

   /**
   * The business date (UTC), in YYYY-MM-DD format.
   * @return bizDate
  **/
  @javax.annotation.Nonnull
  public LocalDate getBizDate() {
    return bizDate;
  }

  public void setBizDate(LocalDate bizDate) {
    this.bizDate = bizDate;
  }


  public ReconDailyStatement tokenId(String tokenId) {
    this.tokenId = tokenId;
    return this;
  }

   /**
   * The token ID, which is the unique identifier of a token.
   * @return tokenId
  **/
  @javax.annotation.Nonnull
  public String getTokenId() {
    return tokenId;
  }

  public void setTokenId(String tokenId) {
    this.tokenId = tokenId;
  }


  public ReconDailyStatement chainId(String chainId) {
    this.chainId = chainId;
    return this;
  }

   /**
   * The chain ID, which is the unique identifier of a blockchain.
   * @return chainId
  **/
  @javax.annotation.Nonnull
  public String getChainId() {
    return chainId;
  }

  public void setChainId(String chainId) {
    this.chainId = chainId;
  }


  public ReconDailyStatement walletId(UUID walletId) {
    this.walletId = walletId;
    return this;
  }

   /**
   * The wallet ID.
   * @return walletId
  **/
  @javax.annotation.Nonnull
  public UUID getWalletId() {
    return walletId;
  }

  public void setWalletId(UUID walletId) {
    this.walletId = walletId;
  }


  public ReconDailyStatement openingBalance(String openingBalance) {
    this.openingBalance = openingBalance;
    return this;
  }

   /**
   * The opening balance at the start of the business date, expressed in the token&#39;s main unit.
   * @return openingBalance
  **/
  @javax.annotation.Nonnull
  public String getOpeningBalance() {
    return openingBalance;
  }

  public void setOpeningBalance(String openingBalance) {
    this.openingBalance = openingBalance;
  }


  public ReconDailyStatement totalDeposit(String totalDeposit) {
    this.totalDeposit = totalDeposit;
    return this;
  }

   /**
   * The total deposit amount during the business date, expressed in the token&#39;s main unit.
   * @return totalDeposit
  **/
  @javax.annotation.Nonnull
  public String getTotalDeposit() {
    return totalDeposit;
  }

  public void setTotalDeposit(String totalDeposit) {
    this.totalDeposit = totalDeposit;
  }


  public ReconDailyStatement depositCount(Integer depositCount) {
    this.depositCount = depositCount;
    return this;
  }

   /**
   * The number of deposits during the business date.
   * @return depositCount
  **/
  @javax.annotation.Nonnull
  public Integer getDepositCount() {
    return depositCount;
  }

  public void setDepositCount(Integer depositCount) {
    this.depositCount = depositCount;
  }


  public ReconDailyStatement totalWithdrawal(String totalWithdrawal) {
    this.totalWithdrawal = totalWithdrawal;
    return this;
  }

   /**
   * The total withdrawal amount during the business date, expressed in the token&#39;s main unit.
   * @return totalWithdrawal
  **/
  @javax.annotation.Nonnull
  public String getTotalWithdrawal() {
    return totalWithdrawal;
  }

  public void setTotalWithdrawal(String totalWithdrawal) {
    this.totalWithdrawal = totalWithdrawal;
  }


  public ReconDailyStatement withdrawalCount(Integer withdrawalCount) {
    this.withdrawalCount = withdrawalCount;
    return this;
  }

   /**
   * The number of withdrawals during the business date.
   * @return withdrawalCount
  **/
  @javax.annotation.Nonnull
  public Integer getWithdrawalCount() {
    return withdrawalCount;
  }

  public void setWithdrawalCount(Integer withdrawalCount) {
    this.withdrawalCount = withdrawalCount;
  }


  public ReconDailyStatement closingBalance(String closingBalance) {
    this.closingBalance = closingBalance;
    return this;
  }

   /**
   * The closing balance at the end of the business date, expressed in the token&#39;s main unit.
   * @return closingBalance
  **/
  @javax.annotation.Nonnull
  public String getClosingBalance() {
    return closingBalance;
  }

  public void setClosingBalance(String closingBalance) {
    this.closingBalance = closingBalance;
  }


  public ReconDailyStatement status(ReconStatementStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nonnull
  public ReconStatementStatus getStatus() {
    return status;
  }

  public void setStatus(ReconStatementStatus status) {
    this.status = status;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ReconDailyStatement instance itself
   */
  public ReconDailyStatement putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReconDailyStatement reconDailyStatement = (ReconDailyStatement) o;
    return Objects.equals(this.bizDate, reconDailyStatement.bizDate) &&
        Objects.equals(this.tokenId, reconDailyStatement.tokenId) &&
        Objects.equals(this.chainId, reconDailyStatement.chainId) &&
        Objects.equals(this.walletId, reconDailyStatement.walletId) &&
        Objects.equals(this.openingBalance, reconDailyStatement.openingBalance) &&
        Objects.equals(this.totalDeposit, reconDailyStatement.totalDeposit) &&
        Objects.equals(this.depositCount, reconDailyStatement.depositCount) &&
        Objects.equals(this.totalWithdrawal, reconDailyStatement.totalWithdrawal) &&
        Objects.equals(this.withdrawalCount, reconDailyStatement.withdrawalCount) &&
        Objects.equals(this.closingBalance, reconDailyStatement.closingBalance) &&
        Objects.equals(this.status, reconDailyStatement.status)&&
        Objects.equals(this.additionalProperties, reconDailyStatement.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bizDate, tokenId, chainId, walletId, openingBalance, totalDeposit, depositCount, totalWithdrawal, withdrawalCount, closingBalance, status, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReconDailyStatement {\n");
    sb.append("    bizDate: ").append(toIndentedString(bizDate)).append("\n");
    sb.append("    tokenId: ").append(toIndentedString(tokenId)).append("\n");
    sb.append("    chainId: ").append(toIndentedString(chainId)).append("\n");
    sb.append("    walletId: ").append(toIndentedString(walletId)).append("\n");
    sb.append("    openingBalance: ").append(toIndentedString(openingBalance)).append("\n");
    sb.append("    totalDeposit: ").append(toIndentedString(totalDeposit)).append("\n");
    sb.append("    depositCount: ").append(toIndentedString(depositCount)).append("\n");
    sb.append("    totalWithdrawal: ").append(toIndentedString(totalWithdrawal)).append("\n");
    sb.append("    withdrawalCount: ").append(toIndentedString(withdrawalCount)).append("\n");
    sb.append("    closingBalance: ").append(toIndentedString(closingBalance)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("biz_date");
    openapiFields.add("token_id");
    openapiFields.add("chain_id");
    openapiFields.add("wallet_id");
    openapiFields.add("opening_balance");
    openapiFields.add("total_deposit");
    openapiFields.add("deposit_count");
    openapiFields.add("total_withdrawal");
    openapiFields.add("withdrawal_count");
    openapiFields.add("closing_balance");
    openapiFields.add("status");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("biz_date");
    openapiRequiredFields.add("token_id");
    openapiRequiredFields.add("chain_id");
    openapiRequiredFields.add("wallet_id");
    openapiRequiredFields.add("opening_balance");
    openapiRequiredFields.add("total_deposit");
    openapiRequiredFields.add("deposit_count");
    openapiRequiredFields.add("total_withdrawal");
    openapiRequiredFields.add("withdrawal_count");
    openapiRequiredFields.add("closing_balance");
    openapiRequiredFields.add("status");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ReconDailyStatement
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ReconDailyStatement.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ReconDailyStatement is not found in the empty JSON string", ReconDailyStatement.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ReconDailyStatement.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("token_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `token_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("token_id").toString()));
      }
      if (!jsonObj.get("chain_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `chain_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("chain_id").toString()));
      }
      if (!jsonObj.get("wallet_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `wallet_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("wallet_id").toString()));
      }
      if (!jsonObj.get("opening_balance").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `opening_balance` to be a primitive type in the JSON string but got `%s`", jsonObj.get("opening_balance").toString()));
      }
      if (!jsonObj.get("total_deposit").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `total_deposit` to be a primitive type in the JSON string but got `%s`", jsonObj.get("total_deposit").toString()));
      }
      if (!jsonObj.get("total_withdrawal").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `total_withdrawal` to be a primitive type in the JSON string but got `%s`", jsonObj.get("total_withdrawal").toString()));
      }
      if (!jsonObj.get("closing_balance").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `closing_balance` to be a primitive type in the JSON string but got `%s`", jsonObj.get("closing_balance").toString()));
      }
      // validate the required field `status`
      ReconStatementStatus.validateJsonElement(jsonObj.get("status"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ReconDailyStatement.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ReconDailyStatement' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ReconDailyStatement> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ReconDailyStatement.class));

       return (TypeAdapter<T>) new TypeAdapter<ReconDailyStatement>() {
           @Override
           public void write(JsonWriter out, ReconDailyStatement value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() == null)
                   obj.addProperty(entry.getKey(), (String) null);
                 else if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ReconDailyStatement read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             ReconDailyStatement instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ReconDailyStatement given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ReconDailyStatement
  * @throws IOException if the JSON string is invalid with respect to ReconDailyStatement
  */
  public static ReconDailyStatement fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ReconDailyStatement.class);
  }

 /**
  * Convert an instance of ReconDailyStatement to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

