/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Review status type, indicating the current stage of the compliance review process.
 */
@JsonAdapter(ReviewStatusType.Adapter.class)
public enum ReviewStatusType {
  UNKNOWN(null),
  
  PENDINGSCREENING("PendingScreening"),
  
  SCREENED("Screened"),
  
  PENDINGDECISION("PendingDecision"),
  
  PENDINGREVIEW("PendingReview"),
  
  APPROVED("Approved"),
  
  REJECTED("Rejected"),
  
  UNSUPPORTED("Unsupported"),
  
  BYPASSED("Bypassed");

  private String value;

  ReviewStatusType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ReviewStatusType fromValue(String value) {
    for (ReviewStatusType b : ReviewStatusType.values()) {
      if (b == UNKNOWN) continue;
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN;
    // throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ReviewStatusType> {
    @Override
    public void write(final JsonWriter jsonWriter, final ReviewStatusType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ReviewStatusType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ReviewStatusType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    ReviewStatusType.fromValue(value);
  }
}

