/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The type of contract call.
 */
@JsonAdapter(TokenizationContractCallType.Adapter.class)
public enum TokenizationContractCallType {
  UNKNOWN(null),
  
  EVM_CONTRACT("EVM_Contract"),
  
  SOL_CONTRACT("SOL_Contract");

  private String value;

  TokenizationContractCallType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static TokenizationContractCallType fromValue(String value) {
    for (TokenizationContractCallType b : TokenizationContractCallType.values()) {
      if (b == UNKNOWN) continue;
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN;
    // throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<TokenizationContractCallType> {
    @Override
    public void write(final JsonWriter jsonWriter, final TokenizationContractCallType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public TokenizationContractCallType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return TokenizationContractCallType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    TokenizationContractCallType.fromValue(value);
  }
}

