/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The direction of the underlying transaction in a Travel Rule operation. - &#x60;DEPOSIT&#x60;: A deposit transaction (verifying the source address). - &#x60;WITHDRAW&#x60;: A withdrawal transaction (verifying the destination address). 
 */
@JsonAdapter(TravelRuleTransactionType.Adapter.class)
public enum TravelRuleTransactionType {
  UNKNOWN(null),
  
  DEPOSIT("DEPOSIT"),
  
  WITHDRAW("WITHDRAW");

  private String value;

  TravelRuleTransactionType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static TravelRuleTransactionType fromValue(String value) {
    for (TravelRuleTransactionType b : TravelRuleTransactionType.values()) {
      if (b == UNKNOWN) continue;
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN;
    // throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<TravelRuleTransactionType> {
    @Override
    public void write(final JsonWriter jsonWriter, final TravelRuleTransactionType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public TravelRuleTransactionType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return TravelRuleTransactionType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    TravelRuleTransactionType.fromValue(value);
  }
}

