/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The action to take. Possible values include:  - &#x60;APPROVE&#x60; : Approve the request and proceed with the operation. - &#x60;REJECT&#x60; : Deny the request and stop the operation. 
 */
@JsonAdapter(TSSCallbackActionType.Adapter.class)
public enum TSSCallbackActionType {
  UNKNOWN(null),
  
  APPROVE("APPROVE"),
  
  REJECT("REJECT");

  private String value;

  TSSCallbackActionType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static TSSCallbackActionType fromValue(String value) {
    for (TSSCallbackActionType b : TSSCallbackActionType.values()) {
      if (b == UNKNOWN) continue;
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN;
    // throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<TSSCallbackActionType> {
    @Override
    public void write(final JsonWriter jsonWriter, final TSSCallbackActionType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public TSSCallbackActionType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return TSSCallbackActionType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    TSSCallbackActionType.fromValue(value);
  }
}

