/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 *  The request type. - &#x60;KeyGen&#x60;: The key gen request. - &#x60;KeyReshare&#x60;: The key reshare request. - &#x60;KeySign&#x60;: The key sign request. - &#x60;KeyShareSign&#x60;: The key share sign request.
 */
@JsonAdapter(TSSRequestTypeEenum.Adapter.class)
public enum TSSRequestTypeEenum {
  UNKNOWN(null),
  
  KEYGEN("KeyGen"),
  
  KEYRESHARE("KeyReshare"),
  
  KEYSIGN("KeySign"),
  
  KEYSHARESIGN("KeyShareSign");

  private String value;

  TSSRequestTypeEenum(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static TSSRequestTypeEenum fromValue(String value) {
    for (TSSRequestTypeEenum b : TSSRequestTypeEenum.values()) {
      if (b == UNKNOWN) continue;
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN;
    // throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<TSSRequestTypeEenum> {
    @Override
    public void write(final JsonWriter jsonWriter, final TSSRequestTypeEenum enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public TSSRequestTypeEenum read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return TSSRequestTypeEenum.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    TSSRequestTypeEenum.fromValue(value);
  }
}

