/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AddTxTokens201Response
 */
public class AddTxTokens201ResponseTest {
    private final AddTxTokens201Response model = new AddTxTokens201Response();

    /**
     * Model tests for AddTxTokens201Response
     */
    @Test
    public void testAddTxTokens201Response() {
        // TODO: test AddTxTokens201Response
    }

    /**
     * Test the property 'tokenIds'
     */
    @Test
    public void tokenIdsTest() {
        // TODO: test tokenIds
    }

}
