/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.BatchLimitsAndLiquidityResult;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BatchLimitsAndLiquidityResponse
 */
public class BatchLimitsAndLiquidityResponseTest {
    private final BatchLimitsAndLiquidityResponse model = new BatchLimitsAndLiquidityResponse();

    /**
     * Model tests for BatchLimitsAndLiquidityResponse
     */
    @Test
    public void testBatchLimitsAndLiquidityResponse() {
        // TODO: test BatchLimitsAndLiquidityResponse
    }

    /**
     * Test the property 'items'
     */
    @Test
    public void itemsTest() {
        // TODO: test items
    }

}
