/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.FundsStatusType;
import com.cobo.waas2.model.KytScreeningsTransactionType;
import com.cobo.waas2.model.ReviewStatusType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ComplianceKytScreeningsUpdateEventData
 */
public class ComplianceKytScreeningsUpdateEventDataTest {
    private final ComplianceKytScreeningsUpdateEventData model = new ComplianceKytScreeningsUpdateEventData();

    /**
     * Model tests for ComplianceKytScreeningsUpdateEventData
     */
    @Test
    public void testComplianceKytScreeningsUpdateEventData() {
        // TODO: test ComplianceKytScreeningsUpdateEventData
    }

    /**
     * Test the property 'dataType'
     */
    @Test
    public void dataTypeTest() {
        // TODO: test dataType
    }

    /**
     * Test the property 'transactionId'
     */
    @Test
    public void transactionIdTest() {
        // TODO: test transactionId
    }

    /**
     * Test the property 'transactionType'
     */
    @Test
    public void transactionTypeTest() {
        // TODO: test transactionType
    }

    /**
     * Test the property 'reviewStatus'
     */
    @Test
    public void reviewStatusTest() {
        // TODO: test reviewStatus
    }

    /**
     * Test the property 'fundsStatus'
     */
    @Test
    public void fundsStatusTest() {
        // TODO: test fundsStatus
    }

    /**
     * Test the property 'updatedTimestamp'
     */
    @Test
    public void updatedTimestampTest() {
        // TODO: test updatedTimestamp
    }

}
