/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.RefundType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateRefundRequest
 */
public class CreateRefundRequestTest {
    private final CreateRefundRequest model = new CreateRefundRequest();

    /**
     * Model tests for CreateRefundRequest
     */
    @Test
    public void testCreateRefundRequest() {
        // TODO: test CreateRefundRequest
    }

    /**
     * Test the property 'requestId'
     */
    @Test
    public void requestIdTest() {
        // TODO: test requestId
    }

    /**
     * Test the property 'merchantId'
     */
    @Test
    public void merchantIdTest() {
        // TODO: test merchantId
    }

    /**
     * Test the property 'payableAmount'
     */
    @Test
    public void payableAmountTest() {
        // TODO: test payableAmount
    }

    /**
     * Test the property 'toAddress'
     */
    @Test
    public void toAddressTest() {
        // TODO: test toAddress
    }

    /**
     * Test the property 'tokenId'
     */
    @Test
    public void tokenIdTest() {
        // TODO: test tokenId
    }

    /**
     * Test the property 'refundType'
     */
    @Test
    public void refundTypeTest() {
        // TODO: test refundType
    }

    /**
     * Test the property 'orderId'
     */
    @Test
    public void orderIdTest() {
        // TODO: test orderId
    }

}
