/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateBankPayoutPyvioRequestBeneficiary
 */
public class CreateBankPayoutPyvioRequestBeneficiaryTest {
    private final CreateBankPayoutPyvioRequestBeneficiary model = new CreateBankPayoutPyvioRequestBeneficiary();

    /**
     * Model tests for CreateBankPayoutPyvioRequestBeneficiary
     */
    @Test
    public void testCreateBankPayoutPyvioRequestBeneficiary() {
        // TODO: test CreateBankPayoutPyvioRequestBeneficiary
    }

    /**
     * Test the property 'accountNo'
     */
    @Test
    public void accountNoTest() {
        // TODO: test accountNo
    }

}
