/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreatePaymentOrderRequest
 */
public class CreatePaymentOrderRequestTest {
    private final CreatePaymentOrderRequest model = new CreatePaymentOrderRequest();

    /**
     * Model tests for CreatePaymentOrderRequest
     */
    @Test
    public void testCreatePaymentOrderRequest() {
        // TODO: test CreatePaymentOrderRequest
    }

    /**
     * Test the property 'merchantId'
     */
    @Test
    public void merchantIdTest() {
        // TODO: test merchantId
    }

    /**
     * Test the property 'tokenId'
     */
    @Test
    public void tokenIdTest() {
        // TODO: test tokenId
    }

    /**
     * Test the property 'fiatCurrency'
     */
    @Test
    public void fiatCurrencyTest() {
        // TODO: test fiatCurrency
    }

    /**
     * Test the property 'fiatAmount'
     */
    @Test
    public void fiatAmountTest() {
        // TODO: test fiatAmount
    }

    /**
     * Test the property 'feeFiatAmount'
     */
    @Test
    public void feeFiatAmountTest() {
        // TODO: test feeFiatAmount
    }

    /**
     * Test the property 'merchantOrderCode'
     */
    @Test
    public void merchantOrderCodeTest() {
        // TODO: test merchantOrderCode
    }

    /**
     * Test the property 'pspOrderCode'
     */
    @Test
    public void pspOrderCodeTest() {
        // TODO: test pspOrderCode
    }

    /**
     * Test the property 'expiredAt'
     */
    @Test
    public void expiredAtTest() {
        // TODO: test expiredAt
    }

}
