/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.AcquiringType;
import com.cobo.waas2.model.CreateSettlement;
import com.cobo.waas2.model.PayoutChannel;
import com.cobo.waas2.model.SettlementType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateSettlementRequestRequest
 */
public class CreateSettlementRequestRequestTest {
    private final CreateSettlementRequestRequest model = new CreateSettlementRequestRequest();

    /**
     * Model tests for CreateSettlementRequestRequest
     */
    @Test
    public void testCreateSettlementRequestRequest() {
        // TODO: test CreateSettlementRequestRequest
    }

    /**
     * Test the property 'requestId'
     */
    @Test
    public void requestIdTest() {
        // TODO: test requestId
    }

    /**
     * Test the property 'acquiringType'
     */
    @Test
    public void acquiringTypeTest() {
        // TODO: test acquiringType
    }

    /**
     * Test the property 'payoutChannel'
     */
    @Test
    public void payoutChannelTest() {
        // TODO: test payoutChannel
    }

    /**
     * Test the property 'settlementType'
     */
    @Test
    public void settlementTypeTest() {
        // TODO: test settlementType
    }

    /**
     * Test the property 'settlements'
     */
    @Test
    public void settlementsTest() {
        // TODO: test settlements
    }

    /**
     * Test the property 'bankAccountId'
     */
    @Test
    public void bankAccountIdTest() {
        // TODO: test bankAccountId
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'remark'
     */
    @Test
    public void remarkTest() {
        // TODO: test remark
    }

}
