/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EstimatedFILFeeSlow
 */
public class EstimatedFILFeeSlowTest {
    private final EstimatedFILFeeSlow model = new EstimatedFILFeeSlow();

    /**
     * Model tests for EstimatedFILFeeSlow
     */
    @Test
    public void testEstimatedFILFeeSlow() {
        // TODO: test EstimatedFILFeeSlow
    }

    /**
     * Test the property 'gasPremium'
     */
    @Test
    public void gasPremiumTest() {
        // TODO: test gasPremium
    }

    /**
     * Test the property 'gasFeeCap'
     */
    @Test
    public void gasFeeCapTest() {
        // TODO: test gasFeeCap
    }

    /**
     * Test the property 'gasLimit'
     */
    @Test
    public void gasLimitTest() {
        // TODO: test gasLimit
    }

    /**
     * Test the property 'gasBase'
     */
    @Test
    public void gasBaseTest() {
        // TODO: test gasBase
    }

}
