/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.Balance;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ListTokenBalancesForFeeStation200ResponseDataInner
 */
public class ListTokenBalancesForFeeStation200ResponseDataInnerTest {
    private final ListTokenBalancesForFeeStation200ResponseDataInner model = new ListTokenBalancesForFeeStation200ResponseDataInner();

    /**
     * Model tests for ListTokenBalancesForFeeStation200ResponseDataInner
     */
    @Test
    public void testListTokenBalancesForFeeStation200ResponseDataInner() {
        // TODO: test ListTokenBalancesForFeeStation200ResponseDataInner
    }

    /**
     * Test the property 'tokenId'
     */
    @Test
    public void tokenIdTest() {
        // TODO: test tokenId
    }

    /**
     * Test the property 'chainId'
     */
    @Test
    public void chainIdTest() {
        // TODO: test chainId
    }

    /**
     * Test the property 'balance'
     */
    @Test
    public void balanceTest() {
        // TODO: test balance
    }

}
