/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.PaymentAssetAmount;
import com.cobo.waas2.model.PaymentAssetOrFiatAmount;
import com.cobo.waas2.model.PaymentFailedReason;
import com.cobo.waas2.model.PaymentPayoutRequestedTarget;
import com.cobo.waas2.model.PaymentPayoutStatus;
import com.cobo.waas2.model.PaymentPayoutTransaction;
import com.cobo.waas2.model.PaymentTokenCommissionFee;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PaymentPayoutUpdateEventData
 */
public class PaymentPayoutUpdateEventDataTest {
    private final PaymentPayoutUpdateEventData model = new PaymentPayoutUpdateEventData();

    /**
     * Model tests for PaymentPayoutUpdateEventData
     */
    @Test
    public void testPaymentPayoutUpdateEventData() {
        // TODO: test PaymentPayoutUpdateEventData
    }

    /**
     * Test the property 'dataType'
     */
    @Test
    public void dataTypeTest() {
        // TODO: test dataType
    }

    /**
     * Test the property 'payoutId'
     */
    @Test
    public void payoutIdTest() {
        // TODO: test payoutId
    }

    /**
     * Test the property 'requestId'
     */
    @Test
    public void requestIdTest() {
        // TODO: test requestId
    }

    /**
     * Test the property 'sourceAccount'
     */
    @Test
    public void sourceAccountTest() {
        // TODO: test sourceAccount
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'requestedAmounts'
     */
    @Test
    public void requestedAmountsTest() {
        // TODO: test requestedAmounts
    }

    /**
     * Test the property 'failedAmounts'
     */
    @Test
    public void failedAmountsTest() {
        // TODO: test failedAmounts
    }

    /**
     * Test the property 'requestedTarget'
     */
    @Test
    public void requestedTargetTest() {
        // TODO: test requestedTarget
    }

    /**
     * Test the property 'transactions'
     */
    @Test
    public void transactionsTest() {
        // TODO: test transactions
    }

    /**
     * Test the property 'actualPayoutAmount'
     */
    @Test
    public void actualPayoutAmountTest() {
        // TODO: test actualPayoutAmount
    }

    /**
     * Test the property 'initiator'
     */
    @Test
    public void initiatorTest() {
        // TODO: test initiator
    }

    /**
     * Test the property 'commissionFees'
     */
    @Test
    public void commissionFeesTest() {
        // TODO: test commissionFees
    }

    /**
     * Test the property 'remark'
     */
    @Test
    public void remarkTest() {
        // TODO: test remark
    }

    /**
     * Test the property 'failedReason'
     */
    @Test
    public void failedReasonTest() {
        // TODO: test failedReason
    }

    /**
     * Test the property 'createdTimestamp'
     */
    @Test
    public void createdTimestampTest() {
        // TODO: test createdTimestamp
    }

    /**
     * Test the property 'updatedTimestamp'
     */
    @Test
    public void updatedTimestampTest() {
        // TODO: test updatedTimestamp
    }

}
