/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.PaymentBulkSendItemStatus;
import com.cobo.waas2.model.PaymentBulkSendItemValidationStatus;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PaymentBulkSendItemEvent
 */
public class PaymentBulkSendItemEventTest {
    private final PaymentBulkSendItemEvent model = new PaymentBulkSendItemEvent();

    /**
     * Model tests for PaymentBulkSendItemEvent
     */
    @Test
    public void testPaymentBulkSendItemEvent() {
        // TODO: test PaymentBulkSendItemEvent
    }

    /**
     * Test the property 'dataType'
     */
    @Test
    public void dataTypeTest() {
        // TODO: test dataType
    }

    /**
     * Test the property 'bulkSendItemId'
     */
    @Test
    public void bulkSendItemIdTest() {
        // TODO: test bulkSendItemId
    }

    /**
     * Test the property 'tokenId'
     */
    @Test
    public void tokenIdTest() {
        // TODO: test tokenId
    }

    /**
     * Test the property 'receivingAddress'
     */
    @Test
    public void receivingAddressTest() {
        // TODO: test receivingAddress
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'txHash'
     */
    @Test
    public void txHashTest() {
        // TODO: test txHash
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'validationStatus'
     */
    @Test
    public void validationStatusTest() {
        // TODO: test validationStatus
    }

    /**
     * Test the property 'failedReason'
     */
    @Test
    public void failedReasonTest() {
        // TODO: test failedReason
    }

    /**
     * Test the property 'bulkSendId'
     */
    @Test
    public void bulkSendIdTest() {
        // TODO: test bulkSendId
    }

    /**
     * Test the property 'requestId'
     */
    @Test
    public void requestIdTest() {
        // TODO: test requestId
    }

    /**
     * Test the property 'sourceAccount'
     */
    @Test
    public void sourceAccountTest() {
        // TODO: test sourceAccount
    }

    /**
     * Test the property 'createdTimestamp'
     */
    @Test
    public void createdTimestampTest() {
        // TODO: test createdTimestamp
    }

    /**
     * Test the property 'updatedTimestamp'
     */
    @Test
    public void updatedTimestampTest() {
        // TODO: test updatedTimestamp
    }

}
