/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.OrderStatus;
import com.cobo.waas2.model.PaymentAssetAmount;
import com.cobo.waas2.model.PaymentAssetOrFiatAmount;
import com.cobo.waas2.model.PaymentOrderDeposit;
import com.cobo.waas2.model.PaymentOrderNoticeType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PaymentOrderUpdateEventData
 */
public class PaymentOrderUpdateEventDataTest {
    private final PaymentOrderUpdateEventData model = new PaymentOrderUpdateEventData();

    /**
     * Model tests for PaymentOrderUpdateEventData
     */
    @Test
    public void testPaymentOrderUpdateEventData() {
        // TODO: test PaymentOrderUpdateEventData
    }

    /**
     * Test the property 'dataType'
     */
    @Test
    public void dataTypeTest() {
        // TODO: test dataType
    }

    /**
     * Test the property 'orderId'
     */
    @Test
    public void orderIdTest() {
        // TODO: test orderId
    }

    /**
     * Test the property 'pspOrderCode'
     */
    @Test
    public void pspOrderCodeTest() {
        // TODO: test pspOrderCode
    }

    /**
     * Test the property 'merchantId'
     */
    @Test
    public void merchantIdTest() {
        // TODO: test merchantId
    }

    /**
     * Test the property 'merchantOrderCode'
     */
    @Test
    public void merchantOrderCodeTest() {
        // TODO: test merchantOrderCode
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'noticeType'
     */
    @Test
    public void noticeTypeTest() {
        // TODO: test noticeType
    }

    /**
     * Test the property 'receiveAddress'
     */
    @Test
    public void receiveAddressTest() {
        // TODO: test receiveAddress
    }

    /**
     * Test the property 'expiredAt'
     */
    @Test
    public void expiredAtTest() {
        // TODO: test expiredAt
    }

    /**
     * Test the property 'requestedAmount'
     */
    @Test
    public void requestedAmountTest() {
        // TODO: test requestedAmount
    }

    /**
     * Test the property 'creditedAmount'
     */
    @Test
    public void creditedAmountTest() {
        // TODO: test creditedAmount
    }

    /**
     * Test the property 'outstandingAmount'
     */
    @Test
    public void outstandingAmountTest() {
        // TODO: test outstandingAmount
    }

    /**
     * Test the property 'feeAmount'
     */
    @Test
    public void feeAmountTest() {
        // TODO: test feeAmount
    }

    /**
     * Test the property 'transactions'
     */
    @Test
    public void transactionsTest() {
        // TODO: test transactions
    }

    /**
     * Test the property 'createdTimestamp'
     */
    @Test
    public void createdTimestampTest() {
        // TODO: test createdTimestamp
    }

    /**
     * Test the property 'updatedTimestamp'
     */
    @Test
    public void updatedTimestampTest() {
        // TODO: test updatedTimestamp
    }

}
