/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.CommissionFee;
import com.cobo.waas2.model.PaymentAssetAmount;
import com.cobo.waas2.model.PaymentFailedReason;
import com.cobo.waas2.model.RefundStatus;
import com.cobo.waas2.model.RefundType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PaymentRefundUpdateEventData
 */
public class PaymentRefundUpdateEventDataTest {
    private final PaymentRefundUpdateEventData model = new PaymentRefundUpdateEventData();

    /**
     * Model tests for PaymentRefundUpdateEventData
     */
    @Test
    public void testPaymentRefundUpdateEventData() {
        // TODO: test PaymentRefundUpdateEventData
    }

    /**
     * Test the property 'dataType'
     */
    @Test
    public void dataTypeTest() {
        // TODO: test dataType
    }

    /**
     * Test the property 'refundId'
     */
    @Test
    public void refundIdTest() {
        // TODO: test refundId
    }

    /**
     * Test the property 'orderId'
     */
    @Test
    public void orderIdTest() {
        // TODO: test orderId
    }

    /**
     * Test the property 'merchantId'
     */
    @Test
    public void merchantIdTest() {
        // TODO: test merchantId
    }

    /**
     * Test the property 'requestId'
     */
    @Test
    public void requestIdTest() {
        // TODO: test requestId
    }

    /**
     * Test the property 'toAddress'
     */
    @Test
    public void toAddressTest() {
        // TODO: test toAddress
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'requestedAmount'
     */
    @Test
    public void requestedAmountTest() {
        // TODO: test requestedAmount
    }

    /**
     * Test the property 'txHash'
     */
    @Test
    public void txHashTest() {
        // TODO: test txHash
    }

    /**
     * Test the property 'refundType'
     */
    @Test
    public void refundTypeTest() {
        // TODO: test refundType
    }

    /**
     * Test the property 'initiator'
     */
    @Test
    public void initiatorTest() {
        // TODO: test initiator
    }

    /**
     * Test the property 'chargeMerchantFee'
     */
    @Test
    public void chargeMerchantFeeTest() {
        // TODO: test chargeMerchantFee
    }

    /**
     * Test the property 'merchantFee'
     */
    @Test
    public void merchantFeeTest() {
        // TODO: test merchantFee
    }

    /**
     * Test the property 'commissionFee'
     */
    @Test
    public void commissionFeeTest() {
        // TODO: test commissionFee
    }

    /**
     * Test the property 'failedReason'
     */
    @Test
    public void failedReasonTest() {
        // TODO: test failedReason
    }

    /**
     * Test the property 'createdTimestamp'
     */
    @Test
    public void createdTimestampTest() {
        // TODO: test createdTimestamp
    }

    /**
     * Test the property 'updatedTimestamp'
     */
    @Test
    public void updatedTimestampTest() {
        // TODO: test updatedTimestamp
    }

}
