/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PaymentAddressUpdateEventData
 */
public class PaymentAddressUpdateEventDataTest {
    private final PaymentAddressUpdateEventData model = new PaymentAddressUpdateEventData();

    /**
     * Model tests for PaymentAddressUpdateEventData
     */
    @Test
    public void testPaymentAddressUpdateEventData() {
        // TODO: test PaymentAddressUpdateEventData
    }

    /**
     * Test the property 'dataType'
     */
    @Test
    public void dataTypeTest() {
        // TODO: test dataType
    }

    /**
     * Test the property 'customPayerId'
     */
    @Test
    public void customPayerIdTest() {
        // TODO: test customPayerId
    }

    /**
     * Test the property 'payerId'
     */
    @Test
    public void payerIdTest() {
        // TODO: test payerId
    }

    /**
     * Test the property 'chain'
     */
    @Test
    public void chainTest() {
        // TODO: test chain
    }

    /**
     * Test the property 'previousAddress'
     */
    @Test
    public void previousAddressTest() {
        // TODO: test previousAddress
    }

    /**
     * Test the property 'updatedAddress'
     */
    @Test
    public void updatedAddressTest() {
        // TODO: test updatedAddress
    }

}
