/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.PaymentAssetAmount;
import com.cobo.waas2.model.PaymentFailedReason;
import com.cobo.waas2.model.PaymentPayInStatus;
import com.cobo.waas2.model.PaymentScreeningMode;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PaymentTopUpUpdateEventData
 */
public class PaymentTopUpUpdateEventDataTest {
    private final PaymentTopUpUpdateEventData model = new PaymentTopUpUpdateEventData();

    /**
     * Model tests for PaymentTopUpUpdateEventData
     */
    @Test
    public void testPaymentTopUpUpdateEventData() {
        // TODO: test PaymentTopUpUpdateEventData
    }

    /**
     * Test the property 'dataType'
     */
    @Test
    public void dataTypeTest() {
        // TODO: test dataType
    }

    /**
     * Test the property 'transactionId'
     */
    @Test
    public void transactionIdTest() {
        // TODO: test transactionId
    }

    /**
     * Test the property 'merchantId'
     */
    @Test
    public void merchantIdTest() {
        // TODO: test merchantId
    }

    /**
     * Test the property 'payerId'
     */
    @Test
    public void payerIdTest() {
        // TODO: test payerId
    }

    /**
     * Test the property 'customPayerId'
     */
    @Test
    public void customPayerIdTest() {
        // TODO: test customPayerId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'screeningMode'
     */
    @Test
    public void screeningModeTest() {
        // TODO: test screeningMode
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'txHash'
     */
    @Test
    public void txHashTest() {
        // TODO: test txHash
    }

    /**
     * Test the property 'topupAddress'
     */
    @Test
    public void topupAddressTest() {
        // TODO: test topupAddress
    }

    /**
     * Test the property 'sourceAddress'
     */
    @Test
    public void sourceAddressTest() {
        // TODO: test sourceAddress
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'failedReason'
     */
    @Test
    public void failedReasonTest() {
        // TODO: test failedReason
    }

    /**
     * Test the property 'createdTimestamp'
     */
    @Test
    public void createdTimestampTest() {
        // TODO: test createdTimestamp
    }

    /**
     * Test the property 'updatedTimestamp'
     */
    @Test
    public void updatedTimestampTest() {
        // TODO: test updatedTimestamp
    }

}
