/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.PaymentAssetAmount;
import com.cobo.waas2.model.PaymentBulkSendExecutionMode;
import com.cobo.waas2.model.PaymentBulkSendStatus;
import com.cobo.waas2.model.PaymentFailedReason;
import com.cobo.waas2.model.PaymentTokenCommissionFee;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PaymentBulkSendUpdateEventData
 */
public class PaymentBulkSendUpdateEventDataTest {
    private final PaymentBulkSendUpdateEventData model = new PaymentBulkSendUpdateEventData();

    /**
     * Model tests for PaymentBulkSendUpdateEventData
     */
    @Test
    public void testPaymentBulkSendUpdateEventData() {
        // TODO: test PaymentBulkSendUpdateEventData
    }

    /**
     * Test the property 'dataType'
     */
    @Test
    public void dataTypeTest() {
        // TODO: test dataType
    }

    /**
     * Test the property 'bulkSendId'
     */
    @Test
    public void bulkSendIdTest() {
        // TODO: test bulkSendId
    }

    /**
     * Test the property 'requestId'
     */
    @Test
    public void requestIdTest() {
        // TODO: test requestId
    }

    /**
     * Test the property 'sourceAccount'
     */
    @Test
    public void sourceAccountTest() {
        // TODO: test sourceAccount
    }

    /**
     * Test the property 'executionMode'
     */
    @Test
    public void executionModeTest() {
        // TODO: test executionMode
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'itemCount'
     */
    @Test
    public void itemCountTest() {
        // TODO: test itemCount
    }

    /**
     * Test the property 'failedItemCount'
     */
    @Test
    public void failedItemCountTest() {
        // TODO: test failedItemCount
    }

    /**
     * Test the property 'notExecutedItemCount'
     */
    @Test
    public void notExecutedItemCountTest() {
        // TODO: test notExecutedItemCount
    }

    /**
     * Test the property 'requestedAmounts'
     */
    @Test
    public void requestedAmountsTest() {
        // TODO: test requestedAmounts
    }

    /**
     * Test the property 'completedAmounts'
     */
    @Test
    public void completedAmountsTest() {
        // TODO: test completedAmounts
    }

    /**
     * Test the property 'failedAmounts'
     */
    @Test
    public void failedAmountsTest() {
        // TODO: test failedAmounts
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'commissionFees'
     */
    @Test
    public void commissionFeesTest() {
        // TODO: test commissionFees
    }

    /**
     * Test the property 'failedReason'
     */
    @Test
    public void failedReasonTest() {
        // TODO: test failedReason
    }

    /**
     * Test the property 'createdTimestamp'
     */
    @Test
    public void createdTimestampTest() {
        // TODO: test createdTimestamp
    }

    /**
     * Test the property 'updatedTimestamp'
     */
    @Test
    public void updatedTimestampTest() {
        // TODO: test updatedTimestamp
    }

}
