/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.SafeTxDecodedData;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SafeTxExtraData
 */
public class SafeTxExtraDataTest {
    private final SafeTxExtraData model = new SafeTxExtraData();

    /**
     * Model tests for SafeTxExtraData
     */
    @Test
    public void testSafeTxExtraData() {
        // TODO: test SafeTxExtraData
    }

    /**
     * Test the property 'to'
     */
    @Test
    public void toTest() {
        // TODO: test to
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'domainHash'
     */
    @Test
    public void domainHashTest() {
        // TODO: test domainHash
    }

    /**
     * Test the property 'messageHash'
     */
    @Test
    public void messageHashTest() {
        // TODO: test messageHash
    }

    /**
     * Test the property 'safeAddress'
     */
    @Test
    public void safeAddressTest() {
        // TODO: test safeAddress
    }

    /**
     * Test the property 'safeTxHash'
     */
    @Test
    public void safeTxHashTest() {
        // TODO: test safeTxHash
    }

    /**
     * Test the property 'safeNonce'
     */
    @Test
    public void safeNonceTest() {
        // TODO: test safeNonce
    }

    /**
     * Test the property 'operation'
     */
    @Test
    public void operationTest() {
        // TODO: test operation
    }

    /**
     * Test the property 'gasTokenAddr'
     */
    @Test
    public void gasTokenAddrTest() {
        // TODO: test gasTokenAddr
    }

    /**
     * Test the property 'safeTxGas'
     */
    @Test
    public void safeTxGasTest() {
        // TODO: test safeTxGas
    }

    /**
     * Test the property 'baseGas'
     */
    @Test
    public void baseGasTest() {
        // TODO: test baseGas
    }

    /**
     * Test the property 'gasPrice'
     */
    @Test
    public void gasPriceTest() {
        // TODO: test gasPrice
    }

    /**
     * Test the property 'refundReceiver'
     */
    @Test
    public void refundReceiverTest() {
        // TODO: test refundReceiver
    }

    /**
     * Test the property 'toContractName'
     */
    @Test
    public void toContractNameTest() {
        // TODO: test toContractName
    }

    /**
     * Test the property 'decodedData'
     */
    @Test
    public void decodedDataTest() {
        // TODO: test decodedData
    }

    /**
     * Test the property 'signature'
     */
    @Test
    public void signatureTest() {
        // TODO: test signature
    }

    /**
     * Test the property 'wei'
     */
    @Test
    public void weiTest() {
        // TODO: test wei
    }

}
