/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.StellarContractCallContractType;
import com.cobo.waas2.model.StellarContractCallTrustLineOperationType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StellarContractCallTrustLineParam
 */
public class StellarContractCallTrustLineParamTest {
    private final StellarContractCallTrustLineParam model = new StellarContractCallTrustLineParam();

    /**
     * Model tests for StellarContractCallTrustLineParam
     */
    @Test
    public void testStellarContractCallTrustLineParam() {
        // TODO: test StellarContractCallTrustLineParam
    }

    /**
     * Test the property 'contractType'
     */
    @Test
    public void contractTypeTest() {
        // TODO: test contractType
    }

    /**
     * Test the property 'tokenId'
     */
    @Test
    public void tokenIdTest() {
        // TODO: test tokenId
    }

    /**
     * Test the property 'operationType'
     */
    @Test
    public void operationTypeTest() {
        // TODO: test operationType
    }

}
