/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.ContractCallDestinationType;
import com.cobo.waas2.model.StellarContractCallContractParam;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StellarContractCallDestination
 */
public class StellarContractCallDestinationTest {
    private final StellarContractCallDestination model = new StellarContractCallDestination();

    /**
     * Model tests for StellarContractCallDestination
     */
    @Test
    public void testStellarContractCallDestination() {
        // TODO: test StellarContractCallDestination
    }

    /**
     * Test the property 'destinationType'
     */
    @Test
    public void destinationTypeTest() {
        // TODO: test destinationType
    }

    /**
     * Test the property 'contractParam'
     */
    @Test
    public void contractParamTest() {
        // TODO: test contractParam
    }

}
