/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.SuspendedTokenOperationType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SuspendedTokenEventData
 */
public class SuspendedTokenEventDataTest {
    private final SuspendedTokenEventData model = new SuspendedTokenEventData();

    /**
     * Model tests for SuspendedTokenEventData
     */
    @Test
    public void testSuspendedTokenEventData() {
        // TODO: test SuspendedTokenEventData
    }

    /**
     * Test the property 'dataType'
     */
    @Test
    public void dataTypeTest() {
        // TODO: test dataType
    }

    /**
     * Test the property 'tokenIds'
     */
    @Test
    public void tokenIdsTest() {
        // TODO: test tokenIds
    }

    /**
     * Test the property 'operationType'
     */
    @Test
    public void operationTypeTest() {
        // TODO: test operationType
    }

}
