/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SwapToken
 */
public class SwapTokenTest {
    private final SwapToken model = new SwapToken();

    /**
     * Model tests for SwapToken
     */
    @Test
    public void testSwapToken() {
        // TODO: test SwapToken
    }

    /**
     * Test the property 'tokenId'
     */
    @Test
    public void tokenIdTest() {
        // TODO: test tokenId
    }

    /**
     * Test the property 'chainId'
     */
    @Test
    public void chainIdTest() {
        // TODO: test chainId
    }

    /**
     * Test the property 'assetId'
     */
    @Test
    public void assetIdTest() {
        // TODO: test assetId
    }

    /**
     * Test the property 'tokenAddress'
     */
    @Test
    public void tokenAddressTest() {
        // TODO: test tokenAddress
    }

    /**
     * Test the property 'minAmount'
     */
    @Test
    public void minAmountTest() {
        // TODO: test minAmount
    }

    /**
     * Test the property 'maxAmount'
     */
    @Test
    public void maxAmountTest() {
        // TODO: test maxAmount
    }

}
