/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ThirdPartyBankAccountInfo
 */
public class ThirdPartyBankAccountInfoTest {
    private final ThirdPartyBankAccountInfo model = new ThirdPartyBankAccountInfo();

    /**
     * Model tests for ThirdPartyBankAccountInfo
     */
    @Test
    public void testThirdPartyBankAccountInfo() {
        // TODO: test ThirdPartyBankAccountInfo
    }

    /**
     * Test the property 'accountNumber'
     */
    @Test
    public void accountNumberTest() {
        // TODO: test accountNumber
    }

    /**
     * Test the property 'accountName'
     */
    @Test
    public void accountNameTest() {
        // TODO: test accountName
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'bankName'
     */
    @Test
    public void bankNameTest() {
        // TODO: test bankName
    }

    /**
     * Test the property 'swiftCode'
     */
    @Test
    public void swiftCodeTest() {
        // TODO: test swiftCode
    }

    /**
     * Test the property 'branchCode'
     */
    @Test
    public void branchCodeTest() {
        // TODO: test branchCode
    }

    /**
     * Test the property 'bankAddress'
     */
    @Test
    public void bankAddressTest() {
        // TODO: test bankAddress
    }

    /**
     * Test the property 'province'
     */
    @Test
    public void provinceTest() {
        // TODO: test province
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'routingValue'
     */
    @Test
    public void routingValueTest() {
        // TODO: test routingValue
    }

    /**
     * Test the property 'iban'
     */
    @Test
    public void ibanTest() {
        // TODO: test iban
    }

}
