/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.ThirdPartyAddress;
import com.cobo.waas2.model.ThirdPartyPersonAttachment;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ThirdPartyPersonInfo
 */
public class ThirdPartyPersonInfoTest {
    private final ThirdPartyPersonInfo model = new ThirdPartyPersonInfo();

    /**
     * Model tests for ThirdPartyPersonInfo
     */
    @Test
    public void testThirdPartyPersonInfo() {
        // TODO: test ThirdPartyPersonInfo
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'nameEn'
     */
    @Test
    public void nameEnTest() {
        // TODO: test nameEn
    }

    /**
     * Test the property 'attachments'
     */
    @Test
    public void attachmentsTest() {
        // TODO: test attachments
    }

    /**
     * Test the property 'idNumber'
     */
    @Test
    public void idNumberTest() {
        // TODO: test idNumber
    }

    /**
     * Test the property 'dateOfBirth'
     */
    @Test
    public void dateOfBirthTest() {
        // TODO: test dateOfBirth
    }

    /**
     * Test the property 'issueDate'
     */
    @Test
    public void issueDateTest() {
        // TODO: test issueDate
    }

    /**
     * Test the property 'expirationDate'
     */
    @Test
    public void expirationDateTest() {
        // TODO: test expirationDate
    }

    /**
     * Test the property 'residentialAddress'
     */
    @Test
    public void residentialAddressTest() {
        // TODO: test residentialAddress
    }

}
