/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.TokenizationBurnTokenParamsBurnsInner;
import com.cobo.waas2.model.TokenizationTokenOperationSource;
import com.cobo.waas2.model.TransactionRequestFee;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TokenizationBurnTokenRequest
 */
public class TokenizationBurnTokenRequestTest {
    private final TokenizationBurnTokenRequest model = new TokenizationBurnTokenRequest();

    /**
     * Model tests for TokenizationBurnTokenRequest
     */
    @Test
    public void testTokenizationBurnTokenRequest() {
        // TODO: test TokenizationBurnTokenRequest
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'burns'
     */
    @Test
    public void burnsTest() {
        // TODO: test burns
    }

    /**
     * Test the property 'appInitiator'
     */
    @Test
    public void appInitiatorTest() {
        // TODO: test appInitiator
    }

    /**
     * Test the property 'fee'
     */
    @Test
    public void feeTest() {
        // TODO: test fee
    }

}
