/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TokenizationSolTokenPermissionParams
 */
public class TokenizationSolTokenPermissionParamsTest {
    private final TokenizationSolTokenPermissionParams model = new TokenizationSolTokenPermissionParams();

    /**
     * Model tests for TokenizationSolTokenPermissionParams
     */
    @Test
    public void testTokenizationSolTokenPermissionParams() {
        // TODO: test TokenizationSolTokenPermissionParams
    }

    /**
     * Test the property 'permanentDelegate'
     */
    @Test
    public void permanentDelegateTest() {
        // TODO: test permanentDelegate
    }

    /**
     * Test the property 'minter'
     */
    @Test
    public void minterTest() {
        // TODO: test minter
    }

    /**
     * Test the property 'freezer'
     */
    @Test
    public void freezerTest() {
        // TODO: test freezer
    }

    /**
     * Test the property 'updater'
     */
    @Test
    public void updaterTest() {
        // TODO: test updater
    }

    /**
     * Test the property 'pauser'
     */
    @Test
    public void pauserTest() {
        // TODO: test pauser
    }

}
