/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.TokenizationActivityStatus;
import com.cobo.waas2.model.TokenizationOperationType;
import com.cobo.waas2.model.TokenizationTokenOperationSource;
import com.cobo.waas2.model.TransactionInitiatorType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TokenizationActivityInfo
 */
public class TokenizationActivityInfoTest {
    private final TokenizationActivityInfo model = new TokenizationActivityInfo();

    /**
     * Model tests for TokenizationActivityInfo
     */
    @Test
    public void testTokenizationActivityInfo() {
        // TODO: test TokenizationActivityInfo
    }

    /**
     * Test the property 'activityId'
     */
    @Test
    public void activityIdTest() {
        // TODO: test activityId
    }

    /**
     * Test the property 'tokenId'
     */
    @Test
    public void tokenIdTest() {
        // TODO: test tokenId
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'initiator'
     */
    @Test
    public void initiatorTest() {
        // TODO: test initiator
    }

    /**
     * Test the property 'initiatorType'
     */
    @Test
    public void initiatorTypeTest() {
        // TODO: test initiatorType
    }

    /**
     * Test the property 'transactionIds'
     */
    @Test
    public void transactionIdsTest() {
        // TODO: test transactionIds
    }

    /**
     * Test the property 'createdTimestamp'
     */
    @Test
    public void createdTimestampTest() {
        // TODO: test createdTimestamp
    }

    /**
     * Test the property 'updatedTimestamp'
     */
    @Test
    public void updatedTimestampTest() {
        // TODO: test updatedTimestamp
    }

}
