/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.TokenizationTokenOperationSource;
import com.cobo.waas2.model.TokenizationUpdateAddressAction;
import com.cobo.waas2.model.TokenizationUpdateAllowlistAddressesParamsAddressesInner;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TokenizationUpdateAllowlistAddressesParams
 */
public class TokenizationUpdateAllowlistAddressesParamsTest {
    private final TokenizationUpdateAllowlistAddressesParams model = new TokenizationUpdateAllowlistAddressesParams();

    /**
     * Model tests for TokenizationUpdateAllowlistAddressesParams
     */
    @Test
    public void testTokenizationUpdateAllowlistAddressesParams() {
        // TODO: test TokenizationUpdateAllowlistAddressesParams
    }

    /**
     * Test the property 'action'
     */
    @Test
    public void actionTest() {
        // TODO: test action
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'addresses'
     */
    @Test
    public void addressesTest() {
        // TODO: test addresses
    }

}
