/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.TokenizationMintTokenParamsMintsInner;
import com.cobo.waas2.model.TokenizationTokenOperationSource;
import com.cobo.waas2.model.TransactionRequestFee;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TokenizationMintTokenRequest
 */
public class TokenizationMintTokenRequestTest {
    private final TokenizationMintTokenRequest model = new TokenizationMintTokenRequest();

    /**
     * Model tests for TokenizationMintTokenRequest
     */
    @Test
    public void testTokenizationMintTokenRequest() {
        // TODO: test TokenizationMintTokenRequest
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'mints'
     */
    @Test
    public void mintsTest() {
        // TODO: test mints
    }

    /**
     * Test the property 'appInitiator'
     */
    @Test
    public void appInitiatorTest() {
        // TODO: test appInitiator
    }

    /**
     * Test the property 'fee'
     */
    @Test
    public void feeTest() {
        // TODO: test fee
    }

    /**
     * Test the property 'requestId'
     */
    @Test
    public void requestIdTest() {
        // TODO: test requestId
    }

}
