/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.TransactionExtraType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TransactionCoreStakeInfo
 */
public class TransactionCoreStakeInfoTest {
    private final TransactionCoreStakeInfo model = new TransactionCoreStakeInfo();

    /**
     * Model tests for TransactionCoreStakeInfo
     */
    @Test
    public void testTransactionCoreStakeInfo() {
        // TODO: test TransactionCoreStakeInfo
    }

    /**
     * Test the property 'extraType'
     */
    @Test
    public void extraTypeTest() {
        // TODO: test extraType
    }

    /**
     * Test the property 'stakeAmount'
     */
    @Test
    public void stakeAmountTest() {
        // TODO: test stakeAmount
    }

    /**
     * Test the property 'timelock'
     */
    @Test
    public void timelockTest() {
        // TODO: test timelock
    }

    /**
     * Test the property 'changeAddress'
     */
    @Test
    public void changeAddressTest() {
        // TODO: test changeAddress
    }

    /**
     * Test the property 'validatorAddress'
     */
    @Test
    public void validatorAddressTest() {
        // TODO: test validatorAddress
    }

    /**
     * Test the property 'rewardAddress'
     */
    @Test
    public void rewardAddressTest() {
        // TODO: test rewardAddress
    }

}
