/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.TransactionExtraType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TransactionFeePayer
 */
public class TransactionFeePayerTest {
    private final TransactionFeePayer model = new TransactionFeePayer();

    /**
     * Model tests for TransactionFeePayer
     */
    @Test
    public void testTransactionFeePayer() {
        // TODO: test TransactionFeePayer
    }

    /**
     * Test the property 'extraType'
     */
    @Test
    public void extraTypeTest() {
        // TODO: test extraType
    }

    /**
     * Test the property 'feePayer'
     */
    @Test
    public void feePayerTest() {
        // TODO: test feePayer
    }

}
