/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.FeeType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TransactionSOLFee
 */
public class TransactionSOLFeeTest {
    private final TransactionSOLFee model = new TransactionSOLFee();

    /**
     * Model tests for TransactionSOLFee
     */
    @Test
    public void testTransactionSOLFee() {
        // TODO: test TransactionSOLFee
    }

    /**
     * Test the property 'baseFee'
     */
    @Test
    public void baseFeeTest() {
        // TODO: test baseFee
    }

    /**
     * Test the property 'rentAmount'
     */
    @Test
    public void rentAmountTest() {
        // TODO: test rentAmount
    }

    /**
     * Test the property 'computeUnitPrice'
     */
    @Test
    public void computeUnitPriceTest() {
        // TODO: test computeUnitPrice
    }

    /**
     * Test the property 'computeUnitLimit'
     */
    @Test
    public void computeUnitLimitTest() {
        // TODO: test computeUnitLimit
    }

    /**
     * Test the property 'feeType'
     */
    @Test
    public void feeTypeTest() {
        // TODO: test feeType
    }

    /**
     * Test the property 'tokenId'
     */
    @Test
    public void tokenIdTest() {
        // TODO: test tokenId
    }

    /**
     * Test the property 'feeUsed'
     */
    @Test
    public void feeUsedTest() {
        // TODO: test feeUsed
    }

    /**
     * Test the property 'estimatedFeeUsed'
     */
    @Test
    public void estimatedFeeUsedTest() {
        // TODO: test estimatedFeeUsed
    }

}
