/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.google.gson.annotations.SerializedName;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TravelRuleTransactionType
 */
public class TravelRuleTransactionTypeTest {
    /**
     * Model tests for TravelRuleTransactionType
     */
    @Test
    public void testTravelRuleTransactionType() {
        // TODO: test TravelRuleTransactionType
    }

}
