/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.TSSCurveType;
import com.cobo.waas2.model.TSSGroupType;
import com.cobo.waas2.model.TSSParticipant;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TSSGroup
 */
public class TSSGroupTest {
    private final TSSGroup model = new TSSGroup();

    /**
     * Model tests for TSSGroup
     */
    @Test
    public void testTSSGroup() {
        // TODO: test TSSGroup
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'canonicalGroupId'
     */
    @Test
    public void canonicalGroupIdTest() {
        // TODO: test canonicalGroupId
    }

    /**
     * Test the property 'protocolGroupId'
     */
    @Test
    public void protocolGroupIdTest() {
        // TODO: test protocolGroupId
    }

    /**
     * Test the property 'protocolType'
     */
    @Test
    public void protocolTypeTest() {
        // TODO: test protocolType
    }

    /**
     * Test the property 'createdTimestamp'
     */
    @Test
    public void createdTimestampTest() {
        // TODO: test createdTimestamp
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'rootExtendedPublicKey'
     */
    @Test
    public void rootExtendedPublicKeyTest() {
        // TODO: test rootExtendedPublicKey
    }

    /**
     * Test the property 'chaincode'
     */
    @Test
    public void chaincodeTest() {
        // TODO: test chaincode
    }

    /**
     * Test the property 'curve'
     */
    @Test
    public void curveTest() {
        // TODO: test curve
    }

    /**
     * Test the property 'threshold'
     */
    @Test
    public void thresholdTest() {
        // TODO: test threshold
    }

    /**
     * Test the property 'participants'
     */
    @Test
    public void participantsTest() {
        // TODO: test participants
    }

}
