/*
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cobo.waas2.model;

import com.cobo.waas2.model.KeyShareHolderGroup;
import com.cobo.waas2.model.MPCProject;
import com.cobo.waas2.model.MPCVault;
import com.cobo.waas2.model.MPCWalletInfo;
import com.cobo.waas2.model.OrgInfo;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TSSKeyShareSignExtra
 */
public class TSSKeyShareSignExtraTest {
    private final TSSKeyShareSignExtra model = new TSSKeyShareSignExtra();

    /**
     * Model tests for TSSKeyShareSignExtra
     */
    @Test
    public void testTSSKeyShareSignExtra() {
        // TODO: test TSSKeyShareSignExtra
    }

    /**
     * Test the property 'org'
     */
    @Test
    public void orgTest() {
        // TODO: test org
    }

    /**
     * Test the property 'project'
     */
    @Test
    public void projectTest() {
        // TODO: test project
    }

    /**
     * Test the property 'vault'
     */
    @Test
    public void vaultTest() {
        // TODO: test vault
    }

    /**
     * Test the property 'wallet'
     */
    @Test
    public void walletTest() {
        // TODO: test wallet
    }

    /**
     * Test the property 'validityKeyShareHolderGroups'
     */
    @Test
    public void validityKeyShareHolderGroupsTest() {
        // TODO: test validityKeyShareHolderGroups
    }

}
